import "./style/Card.css";
import img1 from "../assets/62b26314d79e45482cbd5670_upload (2).png";
import img2 from "../assets/62b2b1feb1666ed2e8385af1_engineering.png";
import img3 from "../assets/62b2b32e88ddeb55f6a89f81_data.png";
function Card() {
  return (
    <>
      <div className="container">
        <div className="small__header">HOW IT WORKS</div>
      </div>
      <div className="container">
        <div className="header">
          Create translated content in minutes,
          <br /> not hours
        </div>
      </div>
      <div className="container">
        <h3>
          Get your videos automatically translated and dubbed with one click.
        </h3>
      </div>
      <div className="cards">
        <div className="card">
          <div className="left__container">
            <img src={img1} alt="" />
          </div>
          <h2>1. Upload & Select</h2>
          <div>
            Upload your video from your computer or share your video link.
          </div>
          <div>
            Choose the original language used in the video. Then choose the
            target language you want it translated to.
          </div>
        </div>
        <div className="card">
          <div className="left__container">
            <img src={img2} alt="" />
          </div>
          <h2>2. process</h2>
          <div>
            Click Run. Soon, you have autogenerated captions, translations and
            voice-over.
          </div>
          <div>The process time is based on the speed of the video.</div>
        </div>
        <div className="card">
          <div className="left__container">
            <img src={img3} alt="" />
          </div>
          <h2>3. Download/Edit & Export</h2>
          <div>
            Once it's done, either click Download Video to finish or Edit Video
            to make changes. ‍
          </div>
          <div>
            Pick from a wide array of customizable tools. When done, choose
            Export.
          </div>
        </div>
      </div>
    </>
  );
}

export default Card;
